import numpy as np
import cv2 as cv
img=cv.imread("C:\\Users\\Asus\\Downloads\\archive (5)\\train\\montelukast 10 MG\\montelukast 10 MG (1) - Copy.jpg")
b,g,r=cv.split(img)
blank=np.zeros(img.shape[:2],dtype='uint8')
blue=cv.merge([b,blank,blank])
green=cv.merge([blank,g,blank])
red=cv.merge([blank,blank,r])
cv.imshow("blue original",blue)
cv.imshow("green original",green)
cv.imshow("Red original",red)
cv.imshow('Blue',b)
cv.imshow("Green",g)
cv.imshow("Red",r)
print(img.shape)
print(b.shape)
print(g.shape)
print(r.shape)
merged_images=cv.merge([b,g,r])
cv.imshow("Image merged",merged_images)
cv.waitKey(0)